import { contactPackageHref } from "@/lib/contact/packages";
import { routes } from "@/lib/routes";

export const webDesignContent = {
  meta: {
    title: "Profesyonel Web Tasarım Fiyatları",
    description:
      "İşletmenize özel profesyonel web sitesi, kurumsal web tasarım, özel yazılım ve dijital ürün geliştirme çözümleri. SALKAY web tasarım paketlerini inceleyin.",
    serviceName: "Professional Web Design & Development",
  },
  hero: {
    eyebrow: "Web Tasarım & Geliştirme",
    titleBefore: "İşletmenize Özel,",
    titleAccent: "Yeni Nesil",
    titleAfter: "Web Siteleri.",
    lead: "Hazır şablonlardan oluşan sıradan web siteleri değil. Markanıza, hedef kitlenize ve iş modelinize özel; hızlı, modern ve büyümeye hazır dijital deneyimler geliştiriyoruz.",
    primaryCta: "Projenizi Konuşalım",
    primaryHref: routes.contact,
    secondaryCta: "Paketleri İncele",
    secondaryHref: "#paketler",
    trust: ["Özel tasarım", "Yüksek performans", "SEO ready", "Modern cloud"],
  },
  intro: {
    eyebrow: "PROJE SEVİYELERİ",
    titleBefore: "İhtiyacınıza göre değil,",
    titleAccent: "Hedefinize",
    titleAfter: "göre başlayın.",
    body: "Her işletmenin dijital ihtiyacı aynı değil. Bu nedenle projelerimizi hazır şablonlar yerine kapsam, hedef ve büyüme planına göre şekillendiriyoruz.",
    line: "Web sitesi · Dijital büyüme · Özel sistemler",
  },
  levels: [
    {
      id: "start",
      index: "01",
      name: "ESSENTIAL",
      descriptor: "KURUMSAL BAŞLANGIÇ",
      featured: false,
      badge: null,
      priceAmount: "29.900",
      priceUnit: "TL’den",
      body: "Dijital dünyada profesyonel bir başlangıç yapmak isteyen işletmeler için.",
      features: [
        "5 sayfaya kadar",
        "Mobil / tablet / desktop uyum",
        "Temel SEO altyapısı",
        "WhatsApp entegrasyonu",
        "SSL güvenliği",
        "Domain bağlantısı",
      ],
      cta: "Essential ile Başlayın",
      href: contactPackageHref("start"),
    },
    {
      id: "business",
      index: "02",
      name: "BUSINESS",
      descriptor: "BÜYÜME ODAKLI",
      featured: true,
      badge: "EN ÇOK TERCİH EDİLEN",
      priceAmount: "49.900",
      priceUnit: "TL’den",
      body: "Dijital görünümünü güçlendirmek ve daha fazla müşteriye ulaşmak isteyen şirketler için.",
      features: [
        "10 sayfaya kadar",
        "Premium animasyonlar",
        "Gelişmiş SEO altyapısı",
        "Otomatik e-posta bildirimleri",
        "Gelişmiş iletişim ve teklif formları",
        "Analytics entegrasyonu",
      ],
      cta: "Business Projesi Başlat",
      href: contactPackageHref("business"),
    },
    {
      id: "professional",
      index: "03",
      name: "PROFESSIONAL",
      descriptor: "DİJİTAL SİSTEM",
      featured: false,
      badge: null,
      priceAmount: "69.900",
      priceUnit: "TL’den",
      body: "Web sitesini aktif bir satış ve müşteri kazanım aracına dönüştürmek isteyen işletmeler için.",
      features: [
        "İleri seviye özel tasarım",
        "CRM bağlantıları",
        "Yönetim paneli seçenekleri",
        "Form otomasyonları",
        "API entegrasyonları",
        "Ölçeklenebilir cloud altyapısı",
      ],
      cta: "Professional Projesi Başlat",
      href: contactPackageHref("professional"),
    },
  ],
  note: {
    primary:
      "Proje kapsamı; sayfa sayısı, özel fonksiyonlar, içerik, entegrasyonlar ve teknik gereksinimlere göre netleştirilir.",
    secondary:
      "Domain kayıt ücretleri, üçüncü taraf lisanslar, reklam bütçeleri ve kapsam dışı özel entegrasyon maliyetleri ayrıca değerlendirilir.",
  },
  signature: {
    index: "04",
    eyebrow: "SALKAY Signature",
    titleBefore: "Standart Bir Web Sitesinden",
    titleAccent: "Daha Fazlası.",
    price: "99.900 TL’den başlayan projeler",
    body: "Markanız için sıfırdan oluşturulan, tasarım ve teknolojinin birlikte çalıştığı özel dijital deneyimler.",
    features: [
      "Creative Direction",
      "Premium UI/UX",
      "Advanced Motion Design",
      "Özel Backend",
      "Yönetim Panelleri",
      "Kullanıcı Hesapları",
      "Müşteri Portalları",
      "Rezervasyon Sistemleri",
      "Ödeme Sistemleri",
      "CRM / ERP Entegrasyonları",
      "AI Entegrasyonları",
      "İşletme Otomasyonları",
    ],
    cta: "Signature Projesi Başlat",
    href: contactPackageHref("signature"),
  },
  custom: {
    index: "05",
    eyebrow: "Özel Yazılım",
    titleBefore: "Fikriniz Bir Web Sitesinden",
    titleAccent: "Daha Büyükse.",
    price: "150.000 TL’den başlayan projeler",
    body: "Özel platformlardan SaaS ürünlerine kadar iş modelinize özel dijital sistemler geliştiriyoruz.",
    capabilities: [
      "SaaS platformları",
      "Müşteri portalları",
      "Marketplace sistemleri",
      "Dashboard’lar",
      "Üyelik sistemleri",
      "Özel CRM",
      "AI destekli uygulamalar",
      "İşletme otomasyonları",
      "API entegrasyonları",
    ],
    cta: "Projenizi Anlatın",
    href: contactPackageHref("custom"),
  },
  care: {
    eyebrow: "Care Planları",
    titleBefore: "Siteniz Güvende, İşiniz",
    titleAccent: "Kesintisiz.",
    intro:
      "Web sitenizin performansı, güvenliği ve güncelliği bizimle güvende. Aylık bakım planlarımızla her zaman bir adım öndesiniz.",
    scope: "Hizmet kapsamı aylık bakım planına göre belirlenir.",
    cta: "Care Planlarını İncele",
    href: contactPackageHref("care"),
    plans: [
      {
        id: "care",
        index: "01",
        name: "CARE",
        kind: "care",
        priceAmount: "2.490",
        priceUnit: "TL / ay",
        cta: "Care Planını Başlat",
        href: contactPackageHref("care"),
        items: [
          "Managed cloud altyapısı",
          "Teknik bakım",
          "Güvenlik güncellemeleri",
          "Deployment yönetimi",
          "Sistem kontrolleri",
          "Belirli kapsamda küçük içerik güncellemeleri",
          "Teknik destek",
          "Performans takibi",
        ],
      },
      {
        id: "care-pro",
        index: "02",
        name: "CARE PRO",
        kind: "pro",
        priceAmount: "4.990",
        priceUnit: "TL / ay",
        cta: "Care Pro Planını Başlat",
        href: contactPackageHref("care-pro"),
        items: [
          "Care kapsamına ek olarak",
          "Öncelikli destek",
          "Düzenli içerik güncellemeleri",
          "SEO kontrolleri",
          "Analytics kontrolleri",
          "Landing page desteği",
          "Conversion iyileştirmeleri",
          "Aylık teknik optimizasyon",
        ],
      },
    ],
  },
  tech: {
    eyebrow: "Teknoloji Altyapısı",
    title: "Modern Teknoloji. Doğru Amaç İçin.",
    items: [
      "Next.js",
      "React",
      "Vercel",
      "PostgreSQL",
      "Neon",
      "Modern Cloud Infrastructure",
    ],
    body: "Teknolojiyi göstermek için değil; daha hızlı, güvenli ve ölçeklenebilir dijital ürünler geliştirmek için kullanıyoruz.",
    core: "Modern Cloud Infrastructure",
    nodes: [
      { index: "01", label: "Frontend", items: ["Next.js", "React"] },
      { index: "02", label: "Cloud", items: ["Vercel", "Modern Cloud"] },
      { index: "03", label: "Data", items: ["PostgreSQL", "Neon"] },
      { index: "04", label: "Scale", items: ["API", "Automation", "Secure Architecture"] },
    ],
    capabilities: [
      {
        index: "01",
        title: "Güvenli",
        body: "Modern güvenlik standartlarını gözeten altyapı yaklaşımı.",
      },
      {
        index: "02",
        title: "Hızlı",
        body: "Performans odaklı geliştirme ve optimizasyon yaklaşımı.",
      },
      {
        index: "03",
        title: "Ölçeklenebilir",
        body: "Büyüyen ihtiyaçlara uyum sağlayabilecek esnek mimari.",
      },
      {
        index: "04",
        title: "Modern Cloud",
        body: "Güncel cloud teknolojileriyle oluşturulan altyapı.",
      },
    ],
    why: {
      eyebrow: "Neden Bu Teknolojiler?",
      body: "Doğru teknolojiyi, doğru amaç için seçiyoruz. Amacımız karmaşık çözümler değil; sürdürülebilir, güvenilir ve büyümeye hazır dijital ürünler geliştirmek.",
      principles: [
        { index: "01", title: "Güncel", body: "Sürekli gelişen modern teknolojiler." },
        { index: "02", title: "Entegre", body: "Birbiriyle uyumlu sistem mimarisi." },
        { index: "03", title: "Veri Odaklı", body: "Veri bütünlüğünü ve sürdürülebilir yapıyı gözeten yaklaşım." },
      ],
    },
  },
  faq: {
    index: "06",
    section: "FAQ",
    eyebrow: "Sık Sorulan Sorular",
    title: "Projenize Başlamadan Önce.",
    body: "Web projenizle ilgili en çok merak edilen konuları bir araya getirdik. Farklı bir sorunuz varsa, ekibimiz her zaman yardımcı olmaktan memnuniyet duyar.",
    supportTitle: "Sorunuzun cevabını bulamadınız mı?",
    supportBody: "Ekibimiz size yardımcı olmaktan memnuniyet duyar.",
    supportCta: "Projenizi Konuşalım",
    supportHref: routes.contact,
    items: [
      {
        question: "Web sitesi ne kadar sürede hazırlanır?",
        answer:
          "Proje kapsamına göre değişir. Kurumsal web projeleri genellikle kapsam, içerik ve entegrasyonlara göre planlanır. Proje başlangıcında net bir teslim planı oluşturulur.",
      },
      {
        question: "Domain ve hosting dahil mi?",
        answer:
          "Domain bağlantısı ve teknik kurulum proje kapsamında yapılabilir. Domain kayıt ücretleri ve üçüncü taraf hizmet bedelleri proje kapsamına göre ayrıca değerlendirilir.",
      },
      {
        question: "Web sitesi mobil uyumlu olacak mı?",
        answer:
          "Evet. Tasarımlar desktop, tablet ve mobil kullanım senaryoları dikkate alınarak responsive olarak geliştirilir.",
      },
      {
        question: "SEO çalışması dahil mi?",
        answer:
          "Paket kapsamına göre temel veya gelişmiş teknik SEO altyapısı uygulanır. Sürekli SEO ve içerik çalışmaları ayrıca planlanabilir.",
      },
      {
        question: "Teslimattan sonra destek veriyor musunuz?",
        answer:
          "Evet. SALKAY Care planları ile bakım, teknik destek, performans ve güncelleme hizmetleri sunulabilir.",
      },
      {
        question: "Özel yazılım geliştirebilir misiniz?",
        answer:
          "Evet. Web sitelerinin yanı sıra müşteri portalları, dashboard’lar, özel CRM sistemleri, SaaS platformları, API entegrasyonları ve AI destekli uygulamalar geliştiriyoruz.",
      },
      {
        question: "Ödeme süreci nasıl ilerliyor?",
        answer:
          "Ödeme planı proje kapsamına göre teklif aşamasında belirlenir. Proje başlamadan önce kapsam, teslimatlar ve ödeme adımları netleştirilir.",
      },
    ],
  },
  finale: {
    eyebrow: "Bir Sonraki Projeniz",
    titleBefore: "Sıradaki Dijital Projenizi",
    titleAccent: "Birlikte Oluşturalım.",
    body: "İşletmenizi ve hedeflerinizi anlatın. İhtiyacınızı analiz edip size uygun çözümü birlikte belirleyelim.",
    primaryCta: "Ücretsiz Ön Görüşme",
    primaryHref: routes.contact,
    secondaryCta: "WhatsApp",
  },
} as const;
