-- AlterEnum
ALTER TYPE "WebsiteStatus" ADD VALUE IF NOT EXISTS 'NO_WEBSITE';
ALTER TYPE "WebsiteStatus" ADD VALUE IF NOT EXISTS 'VERY_WEAK';
ALTER TYPE "WebsiteStatus" ADD VALUE IF NOT EXISTS 'WEAK';
ALTER TYPE "WebsiteStatus" ADD VALUE IF NOT EXISTS 'IMPROVABLE';
ALTER TYPE "WebsiteStatus" ADD VALUE IF NOT EXISTS 'VERY_GOOD';
ALTER TYPE "WebsiteStatus" ADD VALUE IF NOT EXISTS 'NOT_VERIFIED';

-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "websiteScore" TYPE DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "leadScore" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "scoreDesign" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "scoreMobile" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "scoreUx" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "scoreConversion" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "scoreTechnical" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "scoreSeo" DOUBLE PRECISION;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "opportunities" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "salesPitch" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "instagram" TEXT;

CREATE INDEX IF NOT EXISTS "Company_leadScore_idx" ON "Company"("leadScore");
CREATE INDEX IF NOT EXISTS "Company_researchedAt_idx" ON "Company"("researchedAt");
